name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Environment setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.23'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Replace version in package.json to be semver compatible
        run: sed -i "s/IN-DEV/$(echo $GITHUB_REF | sed 's/refs\/tags\///')/" package.json
      
      # Install dependencies
      - name: Install dependencies
        run: pnpm install
      
      # Build
      - name: Build
        run: pnpm build
      
      # Publish to registries
      - name: Publish package on NPM
        run: pnpm publish . --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
