name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Environment setup
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.23'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Replace version in package.json to be semver compatible
        run: sed -i "s/IN-DEV/$(echo $GITHUB_REF | sed 's/refs\/tags\///')/" package.json
      
      # Install dependencies
      - name: Install go dependencies
        run: go mod download
      - name: Install npm dependencies
        run: pnpm install

      # Build
      - name: Build
        run: pnpm build

      # Zip and Tar binaries
      - name: Tar binaries
        run: tar -czf binaries.tar.gz bin/
      - name: Zip binaries
        run: zip -r binaries.zip bin/

      # Publish to npm, gh pages and releases
      - name: Publish package on NPM
        run: pnpm publish . --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
      - name: Publish Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
      - name: Upload binaries tar to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload binaries zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: binaries.zip
          tag: ${{ github.ref }}
          overwrite: true
